version: '3.4'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host
        
  apm:
    image: docker.elastic.co/apm/apm-server:7.5.0
    command: -strict.perms=false
    ports:
      - target: 8200
        published: 8200
        protocol: tcp
        mode: host

volumes:
  esdata:


